name: Deploy to Vercel

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Copy .vercel folder based on environment
        run: |
          if [ ${{ github.ref }} == 'refs/heads/dev' ]; then
            cp -r ./.vercel.dev ./.vercel
          else
            cp -r ./.vercel.prod ./.vercel
          fi

      - name: Deploy to Vercel
        run: |
          npx vercel --prod --yes --token ${{ secrets.GEOME7RIC_VERCEL_TOKEN }}
